package com.example.smartshopper.services;

import com.example.smartshopper.common.Constants;
import com.example.smartshopper.models.Comment;
import com.example.smartshopper.models.Deal;
import com.google.firebase.database.ServerValue;
import com.example.smartshopper.models.User;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;

public class RTDBService {
    FirebaseDatabase database = FirebaseDatabase.getInstance();

    public RTDBService() {
    }

    // Define Queries here

    // Get all for particular
    public Query getAll(String child) {
        return database.getReference().child(child);
    }

    //Get user by username
    public Query getUser(String username) {
        return database.getReference().child(Constants.USERS).orderByChild(Constants.USERNAME).equalTo(username);
    }

    public Query getUserByEmailAddress(String emailAddress) {
        return database.getReference().child(Constants.USERS).orderByChild(Constants.EMAIL).equalTo(emailAddress);
    }

    //Get user by userID (key)
    public Query getUserByKey(String key) {
        return database.getReference().child(Constants.USERS).child(key);
    }

    // Get deal by dealID (key)
    public Query getDeal(String key) {
        return database.getReference().child(Constants.DEALS).child(key);
    }

    // Get comment by commentID (key)
    public Query getComment(String key) {
        return database.getReference().child(Constants.COMMENTS).child(key);
    }

    public Query getRepsonses(String dealKey, String commentKey){
        return database
                .getReference()
                .child(Constants.DEALS)
                .child(dealKey)
                .child(Constants.COMMENTS)
                .child(commentKey)
                .child(Constants.Responses);
    }

    // Get most upvoted deals
    public Query getBestDeals() {
        return database.getReference().child(Constants.DEALS).orderByChild(Constants.UPVOTES);
    }

    // Get deals saved by user
    // TODO: Change argument from String to User once we are able to getCurrentUser
    public Query getSavedDeals(String userID) {
        return database.getReference().child(Constants.USERS).child(userID).child(Constants.SAVED_DEALS);
    }

    // Get deals posted by user
    public Query getPostedDeals(User user) {
        return database.getReference().child(Constants.DEALS).orderByChild(Constants.DEAL_POSTED_BY).equalTo(user.getUsername());
    }

    // Get comments posted by user
    public Query getComments(User user) {
        return database.getReference().child(Constants.DEALS).orderByChild(Constants.COMMENTS).equalTo(user.getUsername());
    }

    // Get comments for a deal
    public Query getComments(Deal deal) {
        return database.getReference().child(Constants.DEALS).child(deal.getDealID()).child(Constants.COMMENTS);
    }

    // Get friends for a user
    public Query getFriends(User user) {
        return database.getReference().child(Constants.USERS).child(user.getUsername()).child(Constants.FRIENDS);
    }

    // Get


    // WRITE METHODS

    /**
     * Writes a user to the database
     *
     * @param user User object to be written
     * @return userID ID that was generated by the database
     */
    public String writeUser(User user) {
        String newUserKey = database.getReference().child(Constants.USERS).push().getKey();
        user.setUserID(newUserKey);
        assert newUserKey != null;
        database.getReference().child(Constants.USERS).child(newUserKey).setValue(user);
        return newUserKey;
    }

    /**
     * Write a new deal to the database
     *
     * @param deal Deal object to be written
     * @return dealID ID that was generated by the database
     */
    public String writeDeal(Deal deal) {
        String key = database.getReference().child(Constants.DEALS).push().getKey();
        deal.setDealID(key);
        assert key != null;
        database.getReference().child(Constants.DEALS).child(key).setValue(deal);
        return key;
    }

    /**
     * Write a new comment to the database
     *
     * @param comment Comment object to be written
     * @return commentID ID that was generated by the database
     */
    public String writeComment(Comment comment, String dealID) {
        String key = database.getReference().child(Constants.DEALS).child(dealID).child(Constants.COMMENTS).push().getKey();
        comment.setCommentID(key);
        assert key != null;
        database.getReference().child(Constants.DEALS).child(dealID).child(Constants.COMMENTS).child(key).setValue(comment);
        return key;
    }

    public void writeResponse(String commentKey, String dealID, Comment response){
        String key = database
                .getReference()
                .child(Constants.DEALS)
                .child(dealID)
                .child(Constants.COMMENTS)
                .child(commentKey)
                .push()
                .getKey();
        response.setCommentID(key);

        assert key != null;
        database
                .getReference()
                .child(Constants.DEALS)
                .child(dealID)
                .child(Constants.COMMENTS)
                .child(commentKey)
                .child(key)
                .setValue(response);
    }

    /**
     * Write a saved deal to the database
     *
     * @param userID ID of the user saving the deal
     * @param deal   the deal being saved
     */
    public void writeSavedDeal(String userID, Deal deal) {
        database.getReference().child(Constants.USERS).child(userID).child(Constants.SAVED_DEALS).push().setValue(deal.getDealID());
    }

    // DELETE METHODS

    public void deleteSavedDeal(String userID, String savedDealKey) {
        database.getReference().child(Constants.USERS).child(userID).child(Constants.SAVED_DEALS).child(savedDealKey).removeValue();
    }

    public void upVoteDeal(String dealId) {
        database.getReference()
                .child(Constants.DEALS)
                .child(dealId)
                .child(Constants.UPVOTES)
                .setValue(ServerValue.increment(1));
    }

    public void downVoteDeal(String dealId) {
        database.getReference()
                .child(Constants.DEALS)
                .child(dealId)
                .child(Constants.DOWNVOTES)
                .setValue(ServerValue.increment(1));
    }

}